//
//  DetailedStockInfoInteractor.swift
//  StocksApp
//
//  Created by Alexey Koryakin on 20.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedStockInfoBusinessLogic {
    func doSomething(request: DetailedStockInfo.Something.Request)
}

protocol DetailedStockInfoDataStore {
    // var name: String { get set }
}

class DetailedStockInfoInteractor: DetailedStockInfoBusinessLogic, DetailedStockInfoDataStore {
    var presenter: DetailedStockInfoPresentationLogic?
    var worker: DetailedStockInfoWorker?
    // var name: String = ""

    // MARK: Do something

    func doSomething(request: DetailedStockInfo.Something.Request) {
        worker = DetailedStockInfoWorker()
        worker?.doSomeWork()

        let response = DetailedStockInfo.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
