//
//  DetailedStockInfoPresenter.swift
//  StocksApp
//
//  Created by Alexey Koryakin on 20.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedStockInfoPresentationLogic
{
  func presentSomething(response: DetailedStockInfo.Something.Response)
}

class DetailedStockInfoPresenter: DetailedStockInfoPresentationLogic
{
  weak var viewController: DetailedStockInfoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DetailedStockInfo.Something.Response)
  {
    let viewModel = DetailedStockInfo.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
