excluded:
  - StocksAppTests

identifier_name:
  excluded:
    - id
    - vc
    - to
    - c
    - h
    - l
    - o
    - pc
    - t

line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

disabled_rules:
  - unused_closure_parameter
  - unused_setter_value
