//
//  StockListViewController.swift
//  StocksApp
//
//  Created by Alexey Koryakin on 20.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StockListDisplayLogic: class {
    func displayLoaded(stock: Stock)
    func displayLoadingError()
}

class StockListViewController: UIViewController, StockListDisplayLogic, UISearchResultsUpdating, UISearchBarDelegate {

    var interactor: StockListBusinessLogic!
    var router: (NSObjectProtocol & StockListRoutingLogic & StockListDataPassing)?

    var stockListTableView: UITableView!
    var dataSource = [Stock]()
    var dataSourceFavourites: [Stock] {
        get {
            return dataSource.filter { stock in
                interactor?.getCurrentFavouriteStatusFor(ticker: stock.ticker) ?? false
            }
        }
    }

    var filteredDataSource = [Stock]()
    //    var hardcodedStocksList = ["AAPL", "TSLA", "MSFT", "PLTR", "AMZN", "GOOG", "ABC", "RMD", "VTR"]
    var hardcodedStocksList = ["TSLA"]
    var isShowingOnlyFavourites = false
    enum StockFavState: String, CaseIterable {
        case all = "Все акции"
        case faved = "Избранное"

    }

    var searchController = UISearchController()

    var lastAnimatedStockCell = -1

    // MARK: - Details
    enum DetailsState {
        case expanded
        case collapsed
    }
    var detailsViewController: DetailsViewController!
    var detailsVisible = false // Expanded
    var nextDetailsState: DetailsState {
        return detailsVisible ? .collapsed : .expanded
    }

    var visualEffectView = UIVisualEffectView()
    var runningAnimations = [UIViewPropertyAnimator]()
    var animationProgressWhenInterrupted: CGFloat = 0

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .systemBackground
        setupTableView()
        setupNavigationItem()
        setupSearchController()
        startDownloadingData()
    }

    // MARK: - Search Controller
    func setupSearchController() {
        searchController.searchResultsUpdater = self
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.enablesReturnKeyAutomatically = false
        searchController.searchBar.returnKeyType = .done
        navigationItem.searchController = searchController
        navigationItem.hidesSearchBarWhenScrolling = false
        searchController.searchBar.scopeButtonTitles = StockFavState.allCases.map { $0.rawValue }
        searchController.searchBar.delegate = self
    }

    func updateSearchResults(for searchController: UISearchController) {
        let searchBar = searchController.searchBar
        let scopeTextValue = searchBar.scopeButtonTitles![searchBar.selectedScopeButtonIndex]
        let scope = scopeTextValue == StockFavState.all.rawValue ? StockFavState.all : StockFavState.faved
        let searchText = searchBar.text!
        switch scope {
        case .all:
            isShowingOnlyFavourites = false
            self.stockListTableView.reloadData()
        case .faved:
            isShowingOnlyFavourites = true
        }
        filterForSearchTextAndScope(searchText: searchText, scope: scope)
    }

    func filterForSearchTextAndScope(searchText: String, scope: StockFavState) {
        filteredDataSource = dataSource.filter { stock in
            let scopeMatch = (scope == .all || (self.interactor?.getCurrentFavouriteStatusFor(ticker: stock.ticker) ?? false))
            if searchController.searchBar.text != "" {
                let tickerTextMatch =  stock.ticker.uppercased().contains(searchText.uppercased())
                let companyNameTextMatch = stock.name.uppercased().contains(searchText.uppercased())
                return scopeMatch && (tickerTextMatch || companyNameTextMatch)
            } else {
                return scopeMatch
            }
        }
        stockListTableView.reloadData()
    }

    func setupTableView() {
        stockListTableView = UITableView(frame: .zero, style: .grouped)
        stockListTableView.delegate = self
        stockListTableView.dataSource = self
        stockListTableView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(stockListTableView)
        // TODO: Сделать расширение для UIView с функцией pin to superview
        stockListTableView.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
        stockListTableView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor).isActive = true
        stockListTableView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
        stockListTableView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true
        stockListTableView.showsVerticalScrollIndicator = false
        stockListTableView.register(StockCell.self, forCellReuseIdentifier: StockCell.reuseIdentifier)
        stockListTableView.backgroundColor = .systemBackground
        stockListTableView.separatorColor = .clear
    }

    func setupNavigationItem() {
        navigationItem.title = "Акции"
        navigationController?.navigationBar.prefersLargeTitles = true
        navigationItem.rightBarButtonItem = UIBarButtonItem(title: "Избранное", style: .plain, target: self, action: #selector(handleFavSelectorTap))
        navigationItem.leftBarButtonItem = UIBarButtonItem(title: "Обновить", style: .plain, target: self, action: #selector(attemptDataUpdate))
    }

    // MARK: - Navigation Bar buttons
    @objc func handleFavSelectorTap(sender: UIBarButtonItem) {
        switch isShowingOnlyFavourites {
        case true:
            sender.title = StockFavState.faved.rawValue
        case false:
            sender.title = StockFavState.all.rawValue

        }
        isShowingOnlyFavourites = !isShowingOnlyFavourites
        stockListTableView.reloadData()
    }

    @objc func attemptDataUpdate() {
        dataSource = [Stock]()
        filteredDataSource = [Stock]()
        startDownloadingData()
    }

    // MARK: - Interactor calls
    func startDownloadingData() {
        #if OFFLINE
        interactor?.loadBundleStockData()
        #else
        hardcodedStocksList.forEach { interactor?.downloadStockDataFor(ticker: $0) }
        #endif
    }

    // MARK: - Presenter functions
    func displayLoaded(stock: Stock) {
        dataSource.append(stock)
        stockListTableView.reloadData()
    }

    func displayLoadingError() {
        let alert = UIAlertController(title: "Ошибка загрузки", message: "Проверьте интернет соединение и нажмите \"Обновить\"", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Хорошо", style: .default, handler: nil))
        self.present(alert, animated: true)
    }
}

// MARK: - StockTableView Protocol Conformance
extension StockListViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard !searchController.isActive else { return filteredDataSource.count }
        guard isShowingOnlyFavourites else { return dataSource.count}
        return dataSourceFavourites.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: StockCell.reuseIdentifier, for: indexPath) as? StockCell else {
            fatalError()
        }
        guard !searchController.isActive else {
            cell.configure(with: filteredDataSource[indexPath.row])
            return cell
        }
        guard isShowingOnlyFavourites else {
            cell.configure(with: dataSource[indexPath.row])
            return cell
        }
        cell.configure(with: dataSourceFavourites[indexPath.row])
        return cell
    }

    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return StockCell.suggestedCellHeight
    }

    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if indexPath.row > lastAnimatedStockCell {
            cell.transform = CGAffineTransform(translationX: self.view.bounds.width / 2, y: 0)
            cell.alpha = 0
            UIView.animate(withDuration: 5.3, delay: Double(indexPath.row) * 0.09, usingSpringWithDamping: 0.7, initialSpringVelocity: 11, options: .curveEaseInOut, animations: {
                cell.transform = .identity
                cell.alpha = 1

            })
            lastAnimatedStockCell = indexPath.row
        }
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        defer {
            present(detailsViewController, animated: true)
        }
        guard isShowingOnlyFavourites else {
            interactor?.sendToDetailsVC(stock: dataSource[indexPath.row])
            return
        }
        guard searchController.isActive else {
            interactor?.sendToDetailsVC(stock: filteredDataSource[indexPath.row])
            return
        }
        interactor?.sendToDetailsVC(stock: dataSourceFavourites[indexPath.row])
    }

    // MARK: - Swipe Actions in TableViewCell
    func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {

        let action = UIContextualAction(style: .normal, title: "Fav") { (action, view, completionHanlder) in
            var stock: Stock!
            // TODO: - Функция-хелпер, сокращяющая дублирование кода
            guard !self.searchController.isActive else {
                stock = self.filteredDataSource[indexPath.row]
                let currentFavStatus = self.interactor?.getCurrentFavouriteStatusFor(ticker: stock.ticker) ?? false
                self.interactor?.setFavouriteStatusFor(ticker: stock.ticker, to: !currentFavStatus)
                self.stockListTableView.reloadData()
                return
            }

            guard self.isShowingOnlyFavourites else {
                stock = self.dataSource[indexPath.row]
                let currentFavStatus = self.interactor?.getCurrentFavouriteStatusFor(ticker: stock.ticker) ?? false
                self.interactor?.setFavouriteStatusFor(ticker: stock.ticker, to: !currentFavStatus)
                return
            }
            stock = self.dataSourceFavourites[indexPath.row]
            let currentFavStatus = self.interactor?.getCurrentFavouriteStatusFor(ticker: stock.ticker) ?? false
            self.interactor?.setFavouriteStatusFor(ticker: stock.ticker, to: !currentFavStatus)
            self.stockListTableView.reloadData()
            completionHanlder(true)
        }

        let favIconConfiguration = UIImage.SymbolConfiguration(pointSize: 22, weight: .bold)

        action.image = UIImage(systemName: "star", withConfiguration: favIconConfiguration)?
            .withRenderingMode(.alwaysOriginal)
            .withTintColor(.white)
        action.backgroundColor = .systemIndigo
        let configuration = UISwipeActionsConfiguration(actions: [action])
        return configuration
    }
}
