//
//  StockListViewController.swift
//  StocksApp
//
//  Created by Alexey Koryakin on 20.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StockListDisplayLogic: class {
    func displayLoaded(stock: Stock)
}

class StockListViewController: UIViewController, StockListDisplayLogic {
    var interactor: StockListBusinessLogic?
    var router: (NSObjectProtocol & StockListRoutingLogic & StockListDataPassing)?
    private let cartTransition = CartTransition()

    var stockListTableView: UITableView!
//    var hardcodedStocksList = ["AAPL", "TSLA", "MSFT", "PLTR", "AMZN", "GOOG", "ABC", "RMD", "VTR"]
        var hardcodedStocksList = ["TSLA"]

    var dataSource = [Stock]()
    var lastAnimatedStockCell = -1

    // MARK: - Details
    enum DetailsState {
        case expanded
        case collapsed
    }
    var detailsViewController: DetailsViewController!
    var detailsVisible = false // Expanded
    var nextDetailsState: DetailsState {
        return detailsVisible ? .collapsed : .expanded
    }
    var detailsViewHeight: CGFloat = 600
    var detailsViewHandleHeight: CGFloat = 120

    var visualEffectView = UIVisualEffectView()
    var runningAnimations = [UIViewPropertyAnimator]()
    var animationProgressWhenInterrupted: CGFloat = 0

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = StockListInteractor()
        let presenter = StockListPresenter()
        let router = StockListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
//        prepareForCellAnimation()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .systemBackground
        navigationItem.title = "Акции"
        navigationController?.navigationBar.prefersLargeTitles = true
        setupTableView()
//        finishCellAnimation()
        setupDetailsVCWithTransition()
        startDownloadingData()
    }

    func setupTableView() {
        stockListTableView = UITableView(frame: .zero, style: .grouped)
        stockListTableView.delegate = self
        stockListTableView.dataSource = self
        stockListTableView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(stockListTableView)
        // TODO: Сделать расширение для UIView с функцией pin to superview
        stockListTableView.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
        stockListTableView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor).isActive = true
        stockListTableView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
        stockListTableView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true
        stockListTableView.showsVerticalScrollIndicator = false
        stockListTableView.register(StockCell.self, forCellReuseIdentifier: StockCell.reuseIdentifier)
        stockListTableView.backgroundColor = .systemBackground
        stockListTableView.separatorColor = .clear
    }

    func setupNavigationItem() {
        navigationItem.title = "Акции"
        navigationController?.navigationBar.prefersLargeTitles = true
        navigationItem.rightBarButtonItem = UIBarButtonItem(title: "Избранное", style: .plain, target: self, action: #selector(handleFavSelectorTap))
//        navigationItem.leftBarButtonItem = UIBarButtonItem(title: "Здаров", style: .plain, target: self, action: nil)
    }

    func setupDetailsVCWithTransition() {
        detailsViewController = DetailsViewController()
        detailsViewController.transitioningDelegate = cartTransition
        detailsViewController.modalPresentationStyle = .custom
    }
    // MARK: - Navigation Bar buttons
    @objc func handleFavSelectorTap(sender: UIBarButtonItem) {
        switch isShowingOnlyFavourites {
        case true:
            sender.title = "Избранное"
        case false:
            sender.title = "Все акции"
        }
        isShowingOnlyFavourites = !isShowingOnlyFavourites
        stockListTableView.reloadData()
    }

    // MARK: - Interactor calls
    func startDownloadingData() {
        hardcodedStocksList.forEach { interactor?.downloadStockDataFor(ticker: $0) }
    }

    // MARK: - Presenter functions
    func displayLoaded(stock: Stock) {
        dataSource.append(stock)
        stockListTableView.reloadData()
    }
}

// MARK: - StockTableView Protocol Conformance
extension StockListViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return dataSource.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: StockCell.reuseIdentifier, for: indexPath) as? StockCell else {
            fatalError()
        }
        cell.configure(with: dataSource[indexPath.row])
        return cell
    }

    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return StockCell.suggestedCellHeight
    }

    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        //        var lastAnimatedItem = -1
        //        guard let cell = stockListTableView.cellForRow(at: indexPath) as? StockCell else { return }
        // TODO: - Добавить анимацию layer.alpha
        if indexPath.row > lastAnimatedStockCell {
            cell.transform = CGAffineTransform(translationX: self.view.bounds.width / 2, y: 0)
            UIView.animate(withDuration: 1.3, delay: Double(indexPath.row) * 0.09, usingSpringWithDamping: 0.7, initialSpringVelocity: 11, options: .curveEaseInOut, animations: {
                cell.transform = .identity
            })
            lastAnimatedStockCell = indexPath.row
        }
    }

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        present(detailsViewController, animated: true)
    }


    // MARK: - Swipe Actions in TableViewCell
    func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {

        let action = UIContextualAction(style: .normal, title: "Fav") { (action, view, completionHanlder) in
            completionHanlder(true)
        }

        let favIconConfiguration = UIImage.SymbolConfiguration(pointSize: 22, weight: .bold)

        action.image = UIImage(systemName: "star", withConfiguration: favIconConfiguration)?
                            .withRenderingMode(.alwaysOriginal)
                            .withTintColor(.label)
        action.backgroundColor = .systemIndigo
        let configuration = UISwipeActionsConfiguration(actions: [action])
        return configuration
    }
}
