//
//  StockListRouter.swift
//  StocksApp
//
//  Created by Alexey Koryakin on 20.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StockListRoutingLogic {
//    func navigateToDetails(source: StockListViewController, destination: DetailedStockInfoViewController)
}

protocol StockListDataPassing {
    var dataStore: StockListDataStore? { get }
}

class StockListRouter: NSObject, StockListRoutingLogic, StockListDataPassing {
    weak var viewController: StockListViewController?
    var dataStore: StockListDataStore?

    // MARK: - Routing

    //  func routeToSomewhere()
    //  {
    //    let destinationVC = segue.destination as! DetailedStockInfoViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  }

    // MARK: - Navigation

//    func navigateToDetails(source: StockListViewController, destination: DetailedStockInfoViewController) {
//        source.show(destination, sender: nil)
//    }

    // MARK: - Passing data

    //    func passDataToDetailedScreen(source: StockListDataStore, destination: inout DetailedStockInfoViewController) {
    //    destination.name = source.name
    //        print("passed")
    //    }
}
