//
//  StockListViewController.swift
//  StocksApp
//
//  Created by Alexey Koryakin on 20.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StockListDisplayLogic: class {
    func displaySomething(viewModel: StockList.Something.ViewModel)
}

class StockListViewController: UIViewController, StockListDisplayLogic {
    var interactor: StockListBusinessLogic?
    var router: (NSObjectProtocol & StockListRoutingLogic & StockListDataPassing)?

    var stockListTableView: UITableView!

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = StockListInteractor()
        let presenter = StockListPresenter()
        let router = StockListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupTableView()
        doSomething()
    }

    func setupTableView() {
        stockListTableView = UITableView(frame: .zero, style: .grouped)
        stockListTableView.delegate = self
        stockListTableView.dataSource = self
        stockListTableView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(stockListTableView)
        stockListTableView.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
        stockListTableView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor).isActive = true
        stockListTableView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: 16).isActive = true
        stockListTableView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: -16).isActive = true
        stockListTableView.showsVerticalScrollIndicator = false
        stockListTableView.register(StockCell.self, forCellReuseIdentifier: StockCell.reuseIdentifier)
        stockListTableView.backgroundColor = .clear
        stockListTableView.separatorColor = .clear
    }
    // MARK: Do something

    func doSomething() {
        let request = StockList.Something.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: StockList.Something.ViewModel) {
        // nameTextField.text = viewModel.name
    }
}

// MARK: - StockTableView Protocol Conformance
extension StockListViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: StockCell.reuseIdentifier, for: indexPath) as? StockCell else {
            fatalError()
        }
        cell.configure(with: Stock(ticker: "AAPL", name: "Apple", currentPrice: 120.31, priceChange: -3.13, isFaved: true))
        return cell
    }

    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return StockCell.suggestedCellHeight
    }

    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        //        guard let cell = collection.cellForItem(at: item.indexPath) as? MainDishCell else { return }
        //        if item.indexPath.row > lastAnimatedItem {
        //        cell.transform = CGAffineTransform(translationX: (stockListTableView.bounds.width + 30) / 2, y: 0)
        //        UIView.animate(withDuration: 1.3, delay: 0.0, usingSpringWithDamping: 0.6, initialSpringVelocity: 11, options: .curveEaseInOut, animations: {
        //            cell.transform = .identity
        //        })
        //            lastAnimatedItem = item.indexPath.row
        //        }

    }
}
