//
//  StockListInteractor.swift
//  StocksApp
//
//  Created by Alexey Koryakin on 20.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StockListBusinessLogic {
    func doSomething(request: StockList.Something.Request)
}

protocol StockListDataStore {
    // var name: String { get set }
}

class StockListInteractor: StockListBusinessLogic, StockListDataStore {
    var presenter: StockListPresentationLogic?
    var worker: StockListWorker?
    // var name: String = ""

    // MARK: Do something

    func doSomething(request: StockList.Something.Request) {
        worker = StockListWorker()
        worker?.doSomeWork()

        let response = StockList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
