//
//  StockListPresenter.swift
//  StocksApp
//
//  Created by Alexey Koryakin on 20.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StockListPresentationLogic {
    func presentLoadedStocksData(response: Stock)
    func presentLoadingFailAlert()
}

class StockListPresenter: StockListPresentationLogic {
    weak var viewController: StockListDisplayLogic?

    // MARK: Do something

    func presentLoadedStocksData(response: Stock) {
        viewController?.displayLoaded(stock: response)
    }

    func presentLoadingFailAlert() {
        // TODO: -Убедиться, что новое уведомление об ошибке не покажется сразу за предыдущим
        viewController?.displayLoadingError()
    }
}
